### ISSUE TITLE
Is crashing also intended as april fools joke?

### ISSUE THREAD

**Issue by JosefFStraka** [AlexModGuy/Citadel#159]
Title says it all.
Crashing randomly while joined on server. Didnt test in solo.
Heres part of stacktrace:
`java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.BakedModel.m_7521_()" because "this.originalModel" is null
	at net.minecraftforge.client.model.BakedModelWrapper.m_7521_(BakedModelWrapper.java:81) ~[forge-1.19.2-43.3.0-universal.jar%23410!/:?] {re:classloading,re:mixin}
	at com.github.alexthe666.citadel.client.game.Tetris.generateNextTetromino(Tetris.java:209) ~[citadel-2.1.4-1.19.jar%23299!/:2.1.4-1.19] {re:classloading}
	at com.github.alexthe666.citadel.client.game.Tetris.reset(Tetris.java:334) ~[citadel-2.1.4-1.19.jar%23299!/:2.1.4-1.19] {re:classloading}
	at com.github.alexthe666.citadel.ClientProxy.clientTick(ClientProxy.java:200) ~[citadel-2.1.4-1.19.jar%23299!/:2.1.4-1.19] {re:classloading}
	at com.github.alexthe666.citadel.__ClientProxy_clientTick_ClientTickEvent.invoke(.dynamic) ~[citadel-2.1.4-1.19.jar%23299!/:2.1.4-1.19] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?] {}`

https://github.com/AlexModGuy/Citadel/blob/8ca51bfdfa09c2d1f2266a25dd54ae64253d71fa/src/main/java/com/github/alexthe666/citadel/client/game/Tetris.java#L203

**Comment by aking4125** [comment]
Getting a similar issue here. Not Enough Crashes is blaming Xenon but it seems to be this: https://bytebin.lucko.me/86ntMculjJ

1.20.1

**Comment by aking4125** [comment]
It seems setting the `"April Fools Content"` to `false` in the `citadel-common` config file may solve the issue. I did it server-side as well just in case and it seems the crashes have stopped.

This might be a widespread issue however. Users in my Medieval MC server are reporting the same thing but the above option seems to fix it for now.

**Comment by DannyIwakura** [comment]
Where do I find the citadel-common file on my server? I have unzipped the Citadel mod and found no configuration file.

**Comment by milkev** [comment]
> Where do I find the citadel-common file on my server? I have unzipped the Citadel mod and found no configuration file.

the config file is in the config folder
