### ISSUE TITLE
Crash when running server

### ISSUE THREAD

**Issue by binlaab** [AlexModGuy/Citadel#169]
I'm getting a crash when running Citadel 2.5.4 in a Forge 48.1.0 server. This is the log:
```
[20:51:06] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forge_server, --fml.forgeVersion, 48.1.0, --fml.mcVersion, 1.20.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230921.100330, @user_jvm_args.txt]
[20:51:06] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: JVM identified as Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39
[20:51:06] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.1.1 starting: java version 17.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[20:51:06] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forge_server
[20:51:06] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/JM/Desktop/forge/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2362!/ Service=ModLauncher Env=SERVER
[20:51:07] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\JM\Desktop\forge\libraries\net\minecraftforge\fmlcore\1.20.2-48.1.0\fmlcore-1.20.2-48.1.0.jar is missing mods.toml file
[20:51:07] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\JM\Desktop\forge\libraries\net\minecraftforge\javafmllanguage\1.20.2-48.1.0\javafmllanguage-1.20.2-48.1.0.jar is missing mods.toml file
[20:51:07] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\JM\Desktop\forge\libraries\net\minecraftforge\lowcodelanguage\1.20.2-48.1.0\lowcodelanguage-1.20.2-48.1.0.jar is missing mods.toml file
[20:51:07] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\JM\Desktop\forge\libraries\net\minecraftforge\mclanguage\1.20.2-48.1.0\mclanguage-1.20.2-48.1.0.jar is missing mods.toml file
[20:51:07] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
[20:51:07] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[20:51:07] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forge_server' with arguments [@user_jvm_args.txt]
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/vanilla.xml
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/gregtechmodernce.xml
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/assortedstorage.xml
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/refinedstorage.xml
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/ic2.xml
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/computercraft.xml
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/mekanism.xml
[20:51:08] [main/INFO] [po.tr.TransformerLib/]: Loaded transformer transformers/ironfurnaces.xml
[20:51:08] [main/FATAL] [mixin/]: Mixin apply failed citadel.mixins.json:MinecraftServerMixin -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on citadel_beforeServerTick could not find any targets matching 'Lnet/minecraft/server/MinecraftServer;runServer()V' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> citadel.mixins.json:MinecraftServerMixin -> Prepare Injections ->  -> handler$zze000$citadel_beforeServerTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on citadel_beforeServerTick could not find any targets matching 'Lnet/minecraft/server/MinecraftServer;runServer()V' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> citadel.mixins.json:MinecraftServerMixin -> Prepare Injections ->  -> handler$zze000$citadel_beforeServerTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2362!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142) ~[modlauncher-10.1.1.jar%2354!/:10.1.1] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:75) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:37) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:418) ~[securemodules-2.2.3.jar:?] {}
        at net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:367) ~[securemodules-2.2.3.jar:?] {}
        at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:383) ~[securemodules-2.2.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
        at java.lang.Class.getMethodsRecursive(Class.java:3543) ~[?:?] {}
        at java.lang.Class.getMethod0(Class.java:3529) ~[?:?] {}
        at java.lang.Class.getMethod(Class.java:2225) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:96) ~[fmlloader-1.20.2-48.1.0.jar%2365!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar%2354!/:?] {}
        at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}
Exception in thread "main" java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:96)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10)
        at net.minecraftforge.bootstrap@1.2.0/net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:37)
        at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:418)
        at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:367)
        at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:383)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3543)
        at java.base/java.lang.Class.getMethod0(Class.java:3529)
        at java.base/java.lang.Class.getMethod(Class.java:2225)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:96)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [citadel.mixins.json:MinecraftServerMixin] from phase [DEFAULT] in config [citadel.mixins.json] FAILED during APPLY
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
        ... 26 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on citadel_beforeServerTick could not find any targets matching 'Lnet/minecraft/server/MinecraftServer;runServer()V' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> citadel.mixins.json:MinecraftServerMixin -> Prepare Injections ->  -> handler$zze000$citadel_beforeServerTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 26 more
```
And the mod list is:
```
alexsmobs-1.22.8.jar
architectury-9.2.14-forge.jar
biggerstacks-1.20.1-1.0.0-all.jar
Botania-1.20.1-444-FORGE.jar
chococraft-1.20.1-forge-0.9.11.jar
citadel-2.5.4-1.20.1.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CreativeCore_FORGE_v2.11.30_mc1.20.1.jar
curios-forge-5.9.1+1.20.1.jar
CyclopsCore-1.20.1-1.19.1.jar
DungeonsArise-1.20.1-2.1.57-release.jar
elevatorid-1.20.1-lex-1.9.jar
EvilCraft-1.20.1-1.2.39.jar
gravestones-v1.15.jar
opf-1.20.1.jar
Patchouli-1.20.1-84-FORGE.jar
PlayerRevive_FORGE_v2.0.25_mc1.20.1.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
Terralith_1.20.1_v2.4.5.jar
Vampirism-1.20.1-1.10.7.jar
Werewolves-1.20.1-2.0.1.0.jar
```

**Comment by AndrewJP2024** [comment]
I suggest down grading the forge server and/or up dating your mods.
The reason is the forge version you provided is 1.20.2 and you have 1.20.1 mods

**Comment by binlaab** [comment]
My bad, for some reason I thought it was 1.20.1. Thanks.
